### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by elleanne**
Make the foundation of the website with flask and python. Has home page and registration page.

### CODE REVIEW

**Comment by kescardoso** [comment]
**Added:**
- Accordion with dataset list.
- User profile, registration, login, logout forms

**Left to implement:**
- More info/functionalities for user profile

**To test the deployed version, try both logged-out and logged-in user:**
- Create a new user on the register page
- Log in and log out to test features

accordion

register

user-login

user-profile

**Comment by kescardoso** [comment]
**NOTE:** must log-In to view this changes

**Added Active inputs, bound to db:**
- New dataset name
- New dataset description
- Last Updated (datepicker with pop-up calendar)
- Is To-Do (on/of switch, displays exclamation mark on main dataset list)

**Left to implement:**
- Option to add external links with jinja tags (for pdf reports retrival)
- Category field

Screenshot 2021-03-28 at 18 37 46

**Comment by Korusuke** [comment]
The `venv/*` directory is not needed to be committed.

**Comment by kescardoso** [comment]
:octocat: **NOTE:** must log-in to view these changes.

**Added Active inputs, bound to db:**
- Category selector
- New dataset name
- New dataset description
- Last Updated (datepicker with pop-up calendar)
- Is To-Do (on/off switch, displays exclamation mark on main dataset list)

**Left to implement:**
- Option to add external links with jinja tags (for pdf reports retrieval)
- Submit button

Screenshot 2021-03-28 at 20 30 02 (2)

Screenshot 2021-03-28 at 20 28 48 (2)

**Review by elleanne — COMMENTED** [review]
Everything looks great! I love the way the sections open up!

**Comment by kescardoso** [comment]
**Added:**
- Allow user to submit new dataset to db with a submit button
- Add custom Materialize select validation (fix Materialize required validation on category selector)
- Add author (created_by) tag to new entries

The Add New Dataset form is now fully functioning with completed data binding to Mongo.
The form also has completed validation functionality.

author

submit_and_validation

**Comment by kescardoso** [comment]
**Added:**
- Allow user to submit new dataset to db with a submit button
- Add custom Materialize select validation (fix Materialize required validation on category selector)
- Add author (created_by) tag to new entries

The Add New Dataset form is now fully functioning with completed data binding to Mongo.
The form also has completed validation functionality.

author

submit_and_validation

**Comment by kescardoso** [comment]
🥳 The basic app structure is now ready 

**Added**
- Data-bonded dataset collapsible list (view and manage)
- Data-bonded register, login, logout and user session
- Data-bonded edit (update) and add (insert) new dataset
- Responsive design
- Form validation
- Activity alerts and confirmations with tooltips and flash message
- User privileges

datasetbucket-edit-add
datasetbucket-logged-in-out
datasetbucket-responsive

I encourage all team members to register and create their own unique account via the heroku deployed version to unveil user privileges. Have fun!

**Comment by elleanne** [comment]
.venv file has been removed.

**Pull request merged**
