### PR TITLE
Update JSON / CSV parsing, commands, and the pdf generation

### PR DESCRIPTION
**Pull request by elleanne**
Add 1 format acceptable for JSON, (Need to add 2 others)
Add dictionary of acceptable labels to read_csv and read_json
Update generatePDF to add dicts as well as arrays

### CODE REVIEW

**Review by sakshigupta265 — CHANGES_REQUESTED** [review]
The changes in read_csv.py files are not working for me, while debugging I found out that 'vR' was being as a common pointer for validRowsName and validRowsIndex.And the value for validRowsName[vR] was going out of bound. I don't think this is a windows-mac error.

**Review by kescardoso — CHANGES_REQUESTED** [review]
The files
`ReadME.md`
`requirements.txt`
must be excluded as they are outdated,
**specially** `requirements.txt` as pulling it to staging now will create a version and deployment conflict.

**Comment by elleanne** [comment]
@sakshigupta265 I think I fixed the out of index error for the vR variable. Can you check and see if it runs for you?
@kescardoso, I deleted all code/text in those 2 files so they don't change the files when they're merged. If delete them, I think that will cause issues.

**Comment by sakshigupta265** [comment]
The changes work for me (**I tested the read_csv file of `kaggle-parse-compileReport` with the runTermainalCommands of `windows-mac`** ). 
Good Job!!😃
But now we cannot merge the `windows-mac` branch to this. 
Probably it's best to create a new branch with the required changes(windows command) and then make a pull request. (I will take care of this😉)
Apart from the fact, this branch doesn't have `windows commands` everything else looks good to me.🎉

**Review by sakshigupta265 — APPROVED** [review]
The changes work for me (**I tested the read_csv file of `kaggle-parse-compileReport` with the runTermainalCommands of `windows-mac`** ). 
Good Job!!😃
But now we cannot merge the `windows-mac` branch to this. 
Probably it's best to create a new branch with the required changes(windows command) and then make a pull request. (I will take care of this😉)
Apart from the fact, this branch doesn't have `windows commands` everything else looks good to me.🎉

**Review by kescardoso — APPROVED** [review]
Deleting the code inside the file (`readme.md` and `requirements.txt`) from this pull request, if changes approved, creates a merging that will delete the code inside these files on the staging branch.
I went ahead and resolved these conflicts by committing the current version of both files from this PR within the `kaggle-parse-compileReport` branch.
All files are clean and conflicts have been resolved 👍🏻

**Pull request merged**
