### PR TITLE
added image analysis

### PR DESCRIPTION
**Pull request by sakshigupta265**
- Please test it and suggest possible changes

### CODE REVIEW

**Review by kescardoso — APPROVED** [review]
awesome, no conflicts on my end 👍🏻

**Review by elleanne — CHANGES_REQUESTED** [review]
- Line 55 of detectFace `cv2.waitKey(0)` was making my program wait forever. But, when I commented it out, things ran fine!
- I added + committed some checking for win32 vs darwin/linux at line 8 of filePath. My os wasn't finding the files the other way.
- Need to delete report.pdf file
- The pdf analysis looks great!!

**Comment by sakshigupta265** [comment]
Nice, I will check on my end if something is breaking

**Review by sakshigupta265 — COMMENTED** [review]
Works for me!!

**Review by sakshigupta265 — COMMENTED** [review]
Works perfectly fine on windows! Can merge it now

**Review by elleanne — APPROVED** [review]

**Pull request merged**
