### PR TITLE
Update runTerminalCommands.py

### PR DESCRIPTION
**Pull request by sakshigupta265**
Added commands for windows as well
Requesting testing on your mac system before the merge

### CODE REVIEW

**Comment by kescardoso** [comment]
Good job @sakshigupta265 -- I resolve the conflicts on the latest pull request, and then I will review this one 👍🏻

**Comment by kescardoso** [comment]
I checked it in my workspace, but I will leave the technical testing for @eliboss and @wyang0216 
Please, only commit pull the file `runTerminalCommands.py` because the flask-app version in the branch `windows-mac` is already out of date.
All looks great to me! Good job! 🥇

**Review by kescardoso — APPROVED** [review]
I checked it in my workspace, but I will leave the technical testing for @eliboss and @wyang0216
Please, only commit/pull the file `runTerminalCommands.py` because the flask-app version in the branch `windows-mac` is already outdated.
All looks great to me! Good job! 🥇

**Review by elleanne — CHANGES_REQUESTED** [review]
I accidentally merged upstream to kaggle-parse-compileReport, but I fixed the conflicts that were caused. I did change a little bit in the findReadableFiles() function, but it was nothing to do with the commands (I made 2 {}, dataResultsFoundJSON and dataResultsFoundCSV). 
The new commands worked for me, so that's 🥳 .
If you can check that what I changed didn't mess up your 
If someone could look over the new changes?

**Review by sakshigupta265 — COMMENTED** [review]
Looks good to me 😁
Extras:
- Adding JSON file parsing commands for windows
- Adding an encoding format while reading JSON files (else it will always mess up while running on windows 😂)

**Review by elleanne — APPROVED** [review]

**Review by elleanne — CHANGES_REQUESTED** [review]
If the changes I made in the kaggle-parse-compileReport branch works for you, we can delete the windows and darwin checks in the read_csv.py file, I think

**Comment by sakshigupta265** [comment]
Yes, it works for me 👍 
I am closing this pull request and creating a new one

**Pull request closed without merging**
