### PR TITLE
Merge branch deployed on elizabeth's branch

### PR DESCRIPTION
**Pull request by elleanne**
Report downloads with analysis from a report

### CODE REVIEW

**Comment by elleanne** [comment]
Sorry about all the arbitrary commits - I was trying to get it deployed on Heroku and had to try so many times to figure out what was going on 😢

**Comment by elleanne** [comment]
The image analysis may not be working well. We need to make sure that the paths are correct.
We also need to delete old datasets. I will add these issues to the project so we can work on them after submission.

**Review by sakshigupta265 — APPROVED** [review]
Looks awesome, Once merged we can add this test URL: https://www.kaggle.com/ronitf/heart-disease-uci in the README for the judges to test. Also, the generated PDF's title is wrong I suppose, it's fetching the wrong name.

**Review by kescardoso — APPROVED** [review]
AWESOME job!

I have reviewed the changes and the merge can be done into `up_to_date` 👍🏻 
Feel free to merge your fork branch to `up_to_date`, and then send a new PR to be reviewed from `up_to_date` into `staging` when you see this.

I just need a break to heal my brain from our sprint, and I will come back to our project asap to do the adjustments in `app.py` and `static` files into `staging` (for conflict solving and pre-deployment testing) and then into `main`. That's because the `up_to_date` branch is already outdated to the new `flask-app` version which is the one we are submitting in `main`). 

Also, I am researching a solution for the dataset post file handling, so the report from analysis can be incorporated into our dataset bucket. I am trying to find an alternative to s3, I found some I will look deeper into. I will also need to update supported file formats in our config vars to accept json and png files.

Great job, go ahead and do the pull! I will take care of the `main` integration asap :champagne: :fireworks:

**Pull request merged**
