### PR TITLE
About page

### LINKED ISSUE #69: Add about page
Add about page to explain bias to the user and explain how we will analyze their data.

### PR DESCRIPTION
**Pull request by elleanne**
Add about page to explain bias and how we analyze the datasets

### CODE REVIEW

**Comment by elleanne** [comment]
@kescardoso I tried really hard to match your formatting and all the details for the HTML templates and rendering the template. I *really* hope I didn't mess anything up. 😅 It works fine on my end, but lmk if I broke something. 😬

**Comment by elleanne** [comment]
D61E4DE0-F537-44F3-8BC4-82ADE1F89999

This is what it should look like

**Review by sakshigupta265 — APPROVED** [review]
I love it 🎉
I think we should keep the ABOUT page as the landing page and have a highlighter UI for showing which tab is open.

**Review by kescardoso — COMMENTED** [review]
@eliboss your commit contains parts of the location session I deleted last night. I just want to make sure the Location sessions will not come back into the staging branch as this would be another day of killing bugs to me and I have to focus on the file handling with mongo db asap. I will check your about-page branch in my vscode before approving changes. Thanks!

@sakshigupta265 I don't have anytime left to continue to work on the UI, I must work on the file handling with mongo today, this is important for the submission to be successful. I am now closing all UI issues and leaving it for after submission if you guys wish to continue developing our project in the future.

Please do not approve this pr before I correct the template. Thanks!

**Review by kescardoso — APPROVED** [review]
I have fixed all templates and app.py updates.

The about page is now the home page for logged-off users, and for logged-in users, the all_datasets page is the home.

The navbar has been rearranged.

**Please, before merging:** Fill out the information on how to retrieve the analysis report from Kaggle for FRONTEND USER.

All good, thanks! 👍🏻

**Comment by kescardoso** [comment]
**Before merging:**
(just in case, as mentioned above) please, fill out the information on how to retrieve the analysis report from Kaggle for FRONTEND USER wherethe screenshot points (the kaggle information for developer is already mentioned on readme)

Screenshot 2021-04-07 at 13 19 23

Thanks! 👍🏻

**Comment by elleanne** [comment]
Deleting this PR because we added needed pages in another, up-to-date branch

**Pull request closed without merging**
